import type { Metadata } from "next";
import { Baskervville, Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { ReactQueryProviders } from "./providers";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const baskerville = Baskervville({
  variable: "--font-baskerville",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${baskerville.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReactQueryProviders>{children}</ReactQueryProviders>
      </body>
    </html>
  );
}
