"""Init base

Revision ID: e30c0042d82e
Revises: 
Create Date: 2026-05-29 10:39:20.007348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e30c0042d82e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('cat_nom', sa.String(length=100), nullable=False),
    sa.Column('cat_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('cat_id'),
    sa.UniqueConstraint('cat_nom')
    )
    op.create_index(op.f('ix_category_cat_id'), 'category', ['cat_id'], unique=False)
    op.create_table('profile',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('profile_email', sa.String(length=255), nullable=False),
    sa.Column('profile_password', sa.String(length=255), nullable=False),
    sa.Column('profile_name', sa.String(length=100), nullable=False),
    sa.Column('profile_firstname', sa.String(length=100), nullable=True),
    sa.Column('profile_avatar', sa.String(length=500), nullable=True),
    sa.Column('profile_role', sa.Enum('CLIENT', 'STYLIST', name='userrole_profile'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('profile_email')
    )
    op.create_index(op.f('ix_profile_profile_id'), 'profile', ['profile_id'], unique=False)
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('order_status', sa.Enum('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='order_status'), nullable=False),
    sa.Column('order_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_order_id'), 'order', ['order_id'], unique=False)
    op.create_table('stylist',
    sa.Column('sty_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('sty_bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sty_id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_stylist_sty_id'), 'stylist', ['sty_id'], unique=False)
    op.create_table('avis',
    sa.Column('avis_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('sty_id', sa.Integer(), nullable=False),
    sa.Column('avis_note', sa.Integer(), nullable=False),
    sa.Column('avis_comment', sa.Text(), nullable=True),
    sa.Column('avis_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sty_id'], ['stylist.sty_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('avis_id')
    )
    op.create_index(op.f('ix_avis_avis_id'), 'avis', ['avis_id'], unique=False)
    op.create_table('creneau',
    sa.Column('cre_id', sa.Integer(), nullable=False),
    sa.Column('sty_id', sa.Integer(), nullable=False),
    sa.Column('cre_debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cre_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cre_est_reserve', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sty_id'], ['stylist.sty_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cre_id')
    )
    op.create_index(op.f('ix_creneau_cre_id'), 'creneau', ['cre_id'], unique=False)
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sty_id', sa.Integer(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_price', sa.Float(), nullable=False),
    sa.Column('product_stock', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('product_tailles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('product_images', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['category.cat_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sty_id'], ['stylist.sty_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_product_product_id'), 'product', ['product_id'], unique=False)
    op.create_table('appointment',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('cre_id', sa.Integer(), nullable=False),
    sa.Column('app_note', sa.Text(), nullable=True),
    sa.Column('app_status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='appointment_status'), nullable=False),
    sa.Column('app_date_reserv', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cre_id'], ['creneau.cre_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('appointment_id'),
    sa.UniqueConstraint('cre_id')
    )
    op.create_index(op.f('ix_appointment_appointment_id'), 'appointment', ['appointment_id'], unique=False)
    op.create_table('cmd_product',
    sa.Column('cmd_prod_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('cmd_prod_qte', sa.Integer(), nullable=False),
    sa.Column('cmd_prod_pu', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('cmd_prod_id')
    )
    op.create_index(op.f('ix_cmd_product_cmd_prod_id'), 'cmd_product', ['cmd_prod_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cmd_product_cmd_prod_id'), table_name='cmd_product')
    op.drop_table('cmd_product')
    op.drop_index(op.f('ix_appointment_appointment_id'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_product_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_creneau_cre_id'), table_name='creneau')
    op.drop_table('creneau')
    op.drop_index(op.f('ix_avis_avis_id'), table_name='avis')
    op.drop_table('avis')
    op.drop_index(op.f('ix_stylist_sty_id'), table_name='stylist')
    op.drop_table('stylist')
    op.drop_index(op.f('ix_order_order_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_profile_profile_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_category_cat_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
