import type { Metadata } from "next";
import "../globals.css";
import Footer from "../components/ui/footer";
import Navbar from "../components/ui/navbar";
import Sidebar from "../components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-full flex flex-col noscrollbar ">
      <div className="grid grid-cols-6">
        <div className="col-span-1">
          <Sidebar />
        </div>
        <div className="col-span-5 mx-auto w-full">
          <Navbar />
          <main className="p-4">{children}</main>
          <Footer />
        </div>
      </div>
    </div>
  );
}
