import type { Metadata } from "next";
import "../globals.css";
import Footer from "../components/ui/footer";
import Navbar from "../components/ui/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-full flex flex-col">
      <Navbar />
      <main>{children}</main>
      <Footer />
    </div>
  );
}
